#Dev

DevConfServerHost=10.204.92.65
DevConfServerName=apsrd8379.uhc.com
DevConfServerPort=8888
DevConfServerUser=ChatORx_TestAgent01
DevConfServerPassword=ChatORx_TestAgent01

#Stage
StgConfServerHost=10.204.92.65
StgConfServerName=apsrd8379.uhc.com
StgConfServerPort=8888
StgConfServerUser=ChatORx_TestAgent01
StgConfServerPassword=ChatORx_TestAgent01

#Prod

ProdConfServerHost=10.204.92.65
ProdConfServerName=apsrd8379.uhc.com
ProdConfServerPort=8888
ProdConfServerUser=ChatORx_TestAgent01
ProdConfServerPassword=ChatORx_TestAgent01

ConfServerClientName=default
ConfServerClientType=SCE
#ConfServerClientName=gms-ELR_1


ConfServerHost=10.204.92.65
ConfServerName=apsrd8379.uhc.com
ConfServerPort=8888

ConfServerUser=ChatORx_TestAgent01
ConfServerPassword=ChatORx_TestAgent01

